let sidebarInfo = [
    {
        id:'20',
        authUrl:'null',
        iconUrl:'el-icon-menu',
        isMenu:0,
        name:'系统管理',
        items:[
            {
                id:'21',
                authUrl:'/projectList',
                iconUrl:'el-icon-document',
                isMenu:1,
                name:'项目操作',
                items:[{}]
            },
            {
                id:'22',
                authUrl:'/proAdminRole',
                iconUrl:'el-icon-document',
                isMenu:1,
                name:'管理员角色操作',
                items:[{}]
            },
            {
                id:'23',
                authUrl:'/proHRrole',
                iconUrl:'el-icon-document',
                isMenu:1,
                name:'HR角色操作',
                items:[{}]
            },
            {
                id:'24',
                authUrl:'/proAccess',
                iconUrl:'el-icon-document',
                isMenu:1,
                name:'权限操作',
                items:[{}]
            },
        ]
    },
    {
        id:'99',
        authUrl:'null',
        iconUrl:'el-icon-menu',
        isMenu:0,
        name:'项目一',
        items:[
            {
                id:'98',
                authUrl:'/home',
                iconUrl:'el-icon-document',
                isMenu:1,
                name:'pro1',
                items:[{}]
            },
            {
                id:'97',
                authUrl:'null',
                iconUrl:'el-icon-menu',
                isMenu:0,
                name:'二级目录',
                items:[
                    {
                        id:'96',
                        authUrl:'/pro2',
                        iconUrl:'el-icon-document',
                        isMenu:1,
                        name:'pro2',
                        items:[{}]
                    }
                ]
            }
        ]
    },
    {
        id:'4',
        authUrl:'null',
        iconUrl:'el-icon-menu',
        isMenu:0,
        name:'项目二',
        items:[
            {
                id:'5',
                authUrl:'/pro3',
                iconUrl:'el-icon-document',
                isMenu:1,
                name:'pro3',
                items:[{}]
            },
            {
                id:'6',
                authUrl:'null',
                iconUrl:'el-icon-menu',
                isMenu:0,
                name:'二级目录',
                items:[
                    {
                        id:'7',
                        authUrl:'/pro4',
                        iconUrl:'el-icon-document',
                        isMenu:1,
                        name:'pro4',
                        items:[{}]
                    }
                ]
            }
        ]
    },
    {
        id:'89',
        authUrl:'null',
        iconUrl:'el-icon-menu',
        isMenu:0,
        name:'项目三',
        items:[
            {
                id:'88',
                authUrl:'/pro5',
                iconUrl:'el-icon-document',
                isMenu:1,
                name:'pro5',
                items:[{}]
            },
            {
                id:'87',
                authUrl:'null',
                iconUrl:'el-icon-menu',
                isMenu:0,
                name:'二级目录',
                items:[
                    {
                        id:'86',
                        authUrl:'/pro6',
                        iconUrl:'el-icon-document',
                        isMenu:1,
                        name:'pro6',
                        items:[{}]
                    }
                ]
            }
        ]
    }
];

export default sidebarInfo;




